class TwoSum(object):

    def __init__(self):
        # initialize your data structure here
        self.counter = {}

    # Add the number to an internal data structure.
    # @param number {int}
    # @return nothing
    def add(self, number):
        # Write your code here
        self.counter[number] = self.counter.get(number, 0) + 1

    # Find if there exists any pair of numbers which sum is equal to the value.
    # @param value {int}
    # @return true if can be found or false
    def find(self, value):
        # Write your code here
        for num, count in self.counter.items():
            target = value - num
            if target in self.counter:
                if target == num and count < 2:
                    continue
                return True
        return False


if __name__ == '__main__':
    s = TwoSum()
    s.add(-12)
    s.add(25)
    s.add(-20)
    s.add(-22)
    s.add(12)
    s.add(-39)
    s.add(11)
    s.add(-15)
    s.add(25)
    s.add(47)
    s.add(-24)
    s.add(18)
    s.add(21)
    s.add(-21)
    s.add(32)
    s.add(-11)
    s.add(-35)
    s.add(37)
    s.add(-8)
    s.add(-18)
    s.add(42)
    s.add(17)
    s.add(16)
    s.add(-46)
    s.add(-27)
    s.add(-34)
    s.add(43)
    s.add(31)
    s.add(-13)
    s.add(44)
    s.add(-6)
    s.add(10)
    s.add(19)
    s.add(12)
    s.add(-11)
    s.add(-12)
    s.add(-25)
    s.add(-39)
    s.add(40)
    s.add(36)
    s.add(-19)
    s.add(-43)
    s.add(12)
    s.add(42)
    s.add(-39)
    s.add(3)
    s.add(-33)
    s.add(-5)
    s.add(0)
    s.add(48)
    s.add(-34)
    s.add(-41)
    s.add(-18)
    s.add(16)
    s.add(43)
    s.add(43)
    s.add(21)
    s.add(-1)
    s.add(-7)
    s.add(7)
    s.add(-13)
    s.add(26)
    s.add(17)
    s.add(-33)
    s.add(-47)
    s.add(23)
    s.add(-7)
    s.add(38)
    s.add(-4)
    s.add(-29)
    s.add(-40)
    s.add(-11)
    s.add(-6)
    s.add(-34)
    s.add(-32)
    s.add(46)
    s.add(25)
    s.add(-6)
    s.add(22)
    s.add(0)
    s.add(-45)
    s.add(-20)
    s.add(-36)
    s.add(3)
    s.add(-46)
    s.add(39)
    s.add(15)
    s.add(19)
    s.add(28)
    s.add(0)
    s.add(29)
    s.add(9)
    s.add(34)
    s.add(22)
    s.add(-8)
    s.add(1)
    s.add(-28)
    s.add(0)
    s.add(40)
    s.add(47)
    s.find(-20)
    s.find(20)
    s.find(3)
    s.find(-42)
    s.find(14)
    s.find(-1)
    s.find(-38)
    s.find(31)
    s.find(40)
    s.find(-31)
    s.find(-26)
    s.find(41)
    s.find(16)
    s.find(-30)
    s.find(-20)
    s.find(24)
    s.find(2)
    s.find(8)
    s.find(32)
    s.find(42)
    s.find(2)
    s.find(4)
    s.find(-50)
    s.find(30)
    s.find(-11)
    s.find(-50)
    s.find(-9)
    s.find(-38)
    s.find(41)
    s.find(-28)
    s.find(-44)
    s.find(-8)
    s.find(27)
    s.find(-35)
    s.find(-8)
    s.find(19)
    s.find(-36)
    s.find(29)
    s.find(-21)
    s.find(24)
    s.find(-43)
    s.find(-30)
    s.find(-11)
    s.find(48)
    s.find(30)
    s.find(49)
    s.find(26)
    s.find(-32)
    s.find(-41)
    s.find(39)
    s.find(40)
    s.find(-46)
    s.find(-28)
    s.find(-15)
    s.find(2)
    s.find(23)
    s.find(-39)
    s.find(-28)
    s.find(-15)
    s.find(42)
    s.find(-1)
    s.find(44)
    s.find(-46)
    s.find(-9)
    s.find(-6)
    s.find(39)
    s.find(9)
    s.find(37)
    s.find(-49)
    s.find(3)
    s.find(14)
    s.find(43)
    s.find(-36)
    s.find(-46)
    s.find(23)
    s.find(2)
    s.find(-6)
    s.find(-48)
    s.find(6)
    s.find(6)
    s.find(40)
    s.find(25)
    s.find(47)
    s.find(2)
    s.find(11)
    s.find(-13)
    s.find(29)
    s.find(24)
    s.find(-21)
    s.find(26)
    s.find(-19)
    s.find(-8)
    s.find(-31)
    s.find(-30)
    s.find(-20)
    s.find(-18)
    s.find(-13)
    s.find(-27)
    s.find(-47)
    s.find(-11)

# Your TwoSum object will be instantiated and called as such:
# twoSum = TwoSum()
# twoSum.add(number)
# twoSum.find(value)
